development:
  refresh_past_hour:
    class: RefreshTopPastHourJob
    queue: background
    args: []
    schedule: every 30 minute

  refresh_past_day:
    class: RefreshTopPastDayJob
    queue: background
    args: []
    schedule: every 30 minute

  refresh_past_week:
    class: RefreshTopPastWeekJob
    queue: background
    args: []
    schedule: every 30 minute

# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day
